# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3c0abcedb0cb4162911cb201fdae4214518e049858f857f07adbd0931e43de2db338a05b902f3c689e8536407cdb86c79882ce41bf47a73140fe76b3d938a55

test:
  secret_key_base: 94dc250f61c104b8fccd8c1e4aa96eb38ccca8a23359ddd4374e6e1c094ec79f5cbadf48525b409641d32c3ce570e349d397ebc51c7edefdc877c0e3c4b2924b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
